// general [ready status]
export const READY_STATUS_LOADING = 'READY_STATUS_LOADING';
export const READY_STATUS_SUCCESS = 'READY_STATUS_SUCCESS';
export const READY_STATUS_ERROR = 'READY_STATUS_ERROR';
export const READY_STATUS_AWAIT = 'READY_STATUS_AWAIT';

// feed actions
export const FEED_LOADING_BEGIN = 'FEED_LOADING_BEGIN';
export const FEED_LOADING_ERROR = 'FEED_LOADING_ERROR';
export const FEED_LOADING_SUCCESS = 'FEED_LOADING_SUCCESS';

// feed image
export const FEED_IMAGE_LOADING_BEGIN = 'FEED_IMAGE_LOADING_BEGIN';
export const FEED_IMAGE_LOADING_ERROR = 'FEED_IMAGE_LOADING_ERROR';
export const FEED_IMAGE_LOADING_SUCCESS = 'FEED_IMAGE_LOADING_SUCCESS';
